version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login  --no-include-email --region us-east-1)
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java"
      - cd authorizationService
      - mvn clean package
      - docker build -t ps-portfolio-auth-ecr .
      - docker tag ps-portfolio-auth-ecr:latest 346916399611.dkr.ecr.us-east-1.amazonaws.com/ps-portfolio-auth-ecr:latest
      
  post_build:
    commands:
      - echo "Post_build"
      - docker push 346916399611.dkr.ecr.us-east-1.amazonaws.com/ps-portfolio-auth-ecr:latest
      - printf '[{"name":"ps-portfolio-auth-ecr","imageUri":"%s"}]' 346916399611.dkr.ecr.us-east-1.amazonaws.com/ps-portfolio-auth-ecr:latest> taskdefinition.json
      - cat taskdefinition.json
      
artifacts:
  files:
    - authorizationService/taskdefinition.json
    